name 'utseresearch-omeka'
version '0.1.0'
author 'Paul Nguyen'
license 'Apache2'
project_page 'http://github.com/utseresearch/puppet-omeka'
dependency 'puppetlabs/stdlib', '>=2.0.0'
dependency 'puppetlabs-mysql'
dependency 'puppetlabs-apache' 
dependency 'spiette-selinux' 
dependency 'camptocamp-archive' 
dependency 'puppetlabs-tomcat' 
dependency 'example42-solr' 
summary 'Puppet module for omeka installation'
description "This puppet module installs and configures an omeka instance. It works by setting up an Apache webserver with PHP/MySQL bindings, and sets itself up for plugins. It optionally includes installation for solr in tomcat and a way of getting your plugins downloaded and extracted into the plugins directory ready for you."
